// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "token": string;
      "model_version": string;
      "is_ocr": boolean;
      "enable_formula": boolean;
      "enable_table": boolean;
      "language": string;
      "page_ranges": string;
      "cache_dir": string;
      "poll_interval_ms": number;
      "poll_timeout_ms": number;
    };
  }
}
