// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "token": string;
      "auto_parse": boolean;
      "model_version": string;
      "is_ocr": boolean;
      "enable_formula": boolean;
      "enable_table": boolean;
      "language": string;
      "page_ranges": string;
      "cache_dir": string;
      "poll_interval_ms": number;
      "poll_timeout_ms": number;
      "batch_parse_concurrency": number;
      "shortcut_parse": string;
      "shortcut_import": string;
      "shortcut_ai": string;
      "import_folder": string;
      "ai.baseUrl": string;
      "ai.apiKey": string;
      "ai.model": string;
      "ai.systemPrompt": string;
      "ai.promptTemplates": string;
      "translate.model": string;
      "translate.targetLang": string;
      "translate.systemPrompt": string;
    };
  }
}
